package systems.vostok.taxi.drive.app.dao.domain.operation

enum CoreOperationNames {
    ADD_CLIENT_OPERATION('ADD_CLIENT'),
    EDIT_CLIENT_OPERATION('EDIT_CLIENT'),
    DELETE_CLIENT_OPERATION('DELETE_CLIENT'),

    ADD_COUNTRY_OPERATION('ADD_COUNTRY'),
    EDIT_COUNTRY_OPERATION('EDIT_COUNTRY'),
    DELETE_COUNTRY_OPERATION('DELETE_COUNTRY'),

    ADD_STATE_OPERATION('ADD_STATE'),
    EDIT_STATE_OPERATION('EDIT_STATE'),
    DELETE_STATE_OPERATION('DELETE_STATE'),

    ADD_CITY_OPERATION('ADD_CITY'),
    EDIT_CITY_OPERATION('EDIT_CITY'),
    DELETE_CITY_OPERATION('DELETE_CITY'),

    ADD_DISTRICT_OPERATION('ADD_DISTRICT'),
    EDIT_DISTRICT_OPERATION('EDIT_DISTRICT'),
    DELETE_DISTRICT_OPERATION('DELETE_DISTRICT'),

    ADD_STREET_OPERATION('ADD_STREET'),
    EDIT_STREET_OPERATION('EDIT_STREET'),
    DELETE_STREET_OPERATION('DELETE_STREET'),

    UPLOAD_DTD_RATES('UPLOAD_DTD_RATES'),
    UPLOAD_CTC_RATES('UPLOAD_CTC_RATES'),

    CREATE_RIDE_OPERATION('CREATE_RIDE')


    String name

    private CoreOperationNames(String name) {
        this.name = name
    }
}
