language: groovy

install: true

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install:
  - chmod +x gradlew

jobs:
  include:
    - stage: Set minor version
      script:
        - git checkout $TRAVIS_BRANCH
        - ./gradlew setMinorVersion -PminorVersion=$TRAVIS_BUILD_NUMBER
        - git add gradle.properties
        - git commit -m 'Update version [skip ci]'
        - git push http://$CREDENTIALS@$PROJECT_PATH HEAD:$TRAVIS_BRANCH

   # - stage: Increment version
   #   script: ./gradlew test

