language: groovy

install: true

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install:
  - chmod +x gradlew

jobs:
  include:
    - stage: Unit test
      script: ./gradlew test

    - stage: Increment version
      script: ./gradlew test
