language: java
dist: trusty

services:
  - docker

addons:
  sonarcloud:
    organization: hurryfox-sonar-org-key
    token:
      secure: $SONAR_TOKEN
    branches:
      - master

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sonar/cache
    - $HOME/.gradle
    - .gradle


before_install:
  - chmod +x gradlew

install: true

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

jobs:
  include:
    - stage: Unit tests & Sonar scaner
      script:
        - ./gradlew test
        - sonar-scanner

#    - stage: Set minor version
#      script:
#        - if [ "$TRAVIS_BRANCH" == "release" ]; then
#            ./gradlew setMinorVersion -PminorVersion=$TRAVIS_BUILD_NUMBER -PciBranchName=$TRAVIS_BRANCH -PciCredentials=$CREDENTIALS -PciProjectPath=$PROJECT_PATH;
#          fi
#
#    - stage: Release to docker
#      script:
#        - if [ "$TRAVIS_BRANCH" == "release" ]; then
#            ./gradlew build;
#            ./gradlew releaseToDocker -PdockerUsername=$DOCKER_USER -PdockerPassword=$DOCKER_PASSWORD;
#          fi




