language: groovy

services:
  - docker

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install:
  - chmod +x gradlew

install: true

jobs:
  include:
    - stage: Unit tests
      script: ./gradlew test

    - stage: Set minor version
      script:
        - if [ "$TRAVIS_BRANCH" == "master" ]; then
              ./gradlew setMinorVersion -PminorVersion=$TRAVIS_BUILD_NUMBER -PciBranchName=$TRAVIS_BRANCH -PciCredentials=$CREDENTIALS -PciProjectPath=$PROJECT_PATH;
          fi

    - stage: Release to docker
      script:
        - if [ "$TRAVIS_BRANCH" == "master" ]; then
              ./gradlew build;
              ./gradlew releaseToDocker -PdockerUsername=$DOCKER_USER -PdockerPassword=$DOCKER_PASSWORD;
          fi



