version: '3.1'

services:
  db:
    image: postgres:10
    ports:
          - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: tda
      POSTGRES_PASSWORD: 123456

  db_support:
    image: cassandra:3.11
    ports:
          - "9042:9042"
    restart: always
