version: '3.1'

services:
  db:
    image: postgres:10
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: tda
      POSTGRES_PASSWORD: 123456

  db_support:
    image: cassandra:3.11
    ports:
      - 9042:9042

  redis:
    image: redis:4.0.11
    ports:
      - 6379:6379

  rabbit:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: 123456
      RABBITMQ_DEFAULT_VHOST: tda


#  db_sso:
#    image: postgres:10
#    ports:
#      - 5431:5432
#    environment:
#      POSTGRES_USER: sso
#      POSTGRES_PASSWORD: 123456
#
#  sso:
#    image: jboss/keycloak:4.0.0.Final
#    environment:
#      DB_VENDOR: POSTGRES
#      DB_ADDR: db_sso
#      DB_DATABASE: sso
#      DB_USER: sso
#      DB_PASSWORD: 123456
#      KEYCLOAK_USER: admin
#      KEYCLOAK_PASSWORD: 123456
#    ports:
#      - 8280:8080
#    depends_on:
#      - db_sso
