
// INSERT price grk -> grd
INSERT INTO %keyspace%.price_dtd (id, distfrom, distto, price)
VALUES (205241, 'grk', 'grd', 110)
IF NOT EXISTS;

// INSERT price grk -> mtf
INSERT INTO %keyspace%.price_dtd (id, distfrom, distto, price)
VALUES (211072, 'grk', 'mtf', 110)
IF NOT EXISTS;

// INSERT price grk -> grk
INSERT INTO %keyspace%.price_dtd (id, distfrom, distto, price)
VALUES (205248, 'grk', 'grk', 110)
IF NOT EXISTS;

// INSERT price grk -> slk
INSERT INTO %keyspace%.price_dtd (id, distfrom, distto, price)
VALUES (216594, 'grk', 'slk', 110)
IF NOT EXISTS;

// INSERT price grk -> vkzl
INSERT INTO %keyspace%.price_dtd (id, distfrom, distto, price)
VALUES (3724679, 'grk', 'vkzl', 110)
IF NOT EXISTS;

// INSERT price grk -> dosa
INSERT INTO %keyspace%.price_dtd (id, distfrom, distto, price)
VALUES (3192057, 'grk', 'dosa', 130)
IF NOT EXISTS;

// INSERT price grk -> sever
INSERT INTO %keyspace%.price_dtd (id, distfrom, distto, price)
VALUES (109433073, 'grk', 'sever', 150)
IF NOT EXISTS;

// INSERT price grk -> crm
INSERT INTO %keyspace%.price_dtd (id, distfrom, distto, price)
VALUES (201406, 'grk', 'crm', 140)
IF NOT EXISTS;

// INSERT price grk -> rts
INSERT INTO %keyspace%.price_dtd (id, distfrom, distto, price)
VALUES (215889, 'grk', 'rts', 150)
IF NOT EXISTS;

// INSERT price grk -> most
INSERT INTO %keyspace%.price_dtd (id, distfrom, distto, price)
VALUES (3460195, 'grk', 'most', 160)
IF NOT EXISTS;

// INSERT price grk -> trz
INSERT INTO %keyspace%.price_dtd (id, distfrom, distto, price)
VALUES (217756, 'grk', 'trz', 150)
IF NOT EXISTS;

// INSERT price grk -> sta
INSERT INTO %keyspace%.price_dtd (id, distfrom, distto, price)
VALUES (216832, 'grk', 'sta', 150)
IF NOT EXISTS;

// INSERT price grk -> hleb
INSERT INTO %keyspace%.price_dtd (id, distfrom, distto, price)
VALUES (3307905, 'grk', 'hleb', 120)
IF NOT EXISTS;

// INSERT price grk -> atp
INSERT INTO %keyspace%.price_dtd (id, distfrom, distto, price)
VALUES (199549, 'grk', 'atp', 120)
IF NOT EXISTS;

// INSERT price grk -> pereezd
INSERT INTO %keyspace%.price_dtd (id, distfrom, distto, price)
VALUES (-678764729, 'grk', 'pereezd', 130)
IF NOT EXISTS;