// INSERT price Spassk -> Adarka
INSERT INTO %keyspace%.price_ctc (id, cityFrom, cityTo, price)
VALUES (143940113, 'Spassk', 'Adarka', 450)
IF NOT EXISTS;

// INSERT price Spassk -> Annenka
INSERT INTO %keyspace%.price_ctc (id, cityFrom, cityTo, price)
VALUES (-1000200441, 'Spassk', 'Annenka', 440)
IF NOT EXISTS;

// INSERT price Spassk -> Aleksandrovka
INSERT INTO %keyspace%.price_ctc (id, cityFrom, cityTo, price)
VALUES (-1640351263, 'Spassk', 'Aleksandrovka', 630)
IF NOT EXISTS;

// INSERT price Spassk -> Busevka
INSERT INTO %keyspace%.price_ctc (id, cityFrom, cityTo, price)
VALUES (92332590, 'Spassk', 'Busevka', 300)
IF NOT EXISTS;

// INSERT price Spassk -> Vishnevka
INSERT INTO %keyspace%.price_ctc (id, cityFrom, cityTo, price)
VALUES (2037741012, 'Spassk', 'Vishnevka', 420)
IF NOT EXISTS;

// INSERT price Spassk -> Vasilkovka
INSERT INTO %keyspace%.price_ctc (id, cityFrom, cityTo, price)
VALUES (-309505244, 'Spassk', 'Vasilkovka', 720)
IF NOT EXISTS;

// INSERT price Spassk -> Gaivoron
INSERT INTO %keyspace%.price_ctc (id, cityFrom, cityTo, price)
VALUES (680140080, 'Spassk', 'Gaivoron', 340)
IF NOT EXISTS;

// INSERT price Spassk -> 26km
INSERT INTO %keyspace%.price_ctc (id, cityFrom, cityTo, price)
VALUES (-1810764627, 'Spassk', '26km', 600)
IF NOT EXISTS;

// INSERT price Spassk -> Duhovskoe
INSERT INTO %keyspace%.price_ctc (id, cityFrom, cityTo, price)
VALUES (-1313336525, 'Spassk', 'Duhovskoe', 850)
IF NOT EXISTS;

// INSERT price Spassk -> Drozdov
INSERT INTO %keyspace%.price_ctc (id, cityFrom, cityTo, price)
VALUES (1778366873, 'Spassk', 'Drozdov', 670)
IF NOT EXISTS;

// INSERT price Spassk -> Evseevka
INSERT INTO %keyspace%.price_ctc (id, cityFrom, cityTo, price)
VALUES (-1077475023, 'Spassk', 'Evseevka', 510)
IF NOT EXISTS;

// INSERT price Spassk -> Arsenev
INSERT INTO %keyspace%.price_ctc (id, cityFrom, cityTo, price)
VALUES (-881066397, 'Spassk', 'Arsenev', 1960)
IF NOT EXISTS;

// INSERT price Spassk -> Anuchino
INSERT INTO %keyspace%.price_ctc (id, cityFrom, cityTo, price)
VALUES (2086611620, 'Spassk', 'Anuchino', 2550)
IF NOT EXISTS;

// INSERT price Spassk -> Luchegorsk
INSERT INTO %keyspace%.price_ctc (id, cityFrom, cityTo, price)
VALUES (954479218, 'Spassk', 'Luchegorsk', 4430)
IF NOT EXISTS;