// INSERT price Спасск -> Адарка
INSERT INTO tda_dev.price_ctc (id, cityFrom, cityTo, price)
VALUES (-1712284993, 'Спасск', 'Адарка', 450)
IF NOT EXISTS;

// INSERT price Спасск -> Анненка
INSERT INTO tda_dev.price_ctc (id, cityFrom, cityTo, price)
VALUES (-120584933, 'Спасск', 'Анненка', 440)
IF NOT EXISTS;

// INSERT price Спасск -> Александровка
INSERT INTO tda_dev.price_ctc (id, cityFrom, cityTo, price)
VALUES (-1238888587, 'Спасск', 'Александровка', 630)
IF NOT EXISTS;

// INSERT price Спасск -> Бусевка
INSERT INTO tda_dev.price_ctc (id, cityFrom, cityTo, price)
VALUES (-1528498201, 'Спасск', 'Бусевка', 300)
IF NOT EXISTS;

// INSERT price Спасск -> Вишневка
INSERT INTO tda_dev.price_ctc (id, cityFrom, cityTo, price)
VALUES (-127244869, 'Спасск', 'Вишневка', 420)
IF NOT EXISTS;

// INSERT price Спасск -> Луговое
INSERT INTO tda_dev.price_ctc (id, cityFrom, cityTo, price)
VALUES (-1672756461, 'Спасск', 'Луговое', 320)
IF NOT EXISTS;

// INSERT price Спасск -> Арсеньев
INSERT INTO tda_dev.price_ctc (id, cityFrom, cityTo, price)
VALUES (-1888156135, 'Спасск', 'Арсеньев', 1960)
IF NOT EXISTS;

// INSERT price Спасск -> Анучино
INSERT INTO tda_dev.price_ctc (id, cityFrom, cityTo, price)
VALUES (67667713, 'Спасск', 'Анучино', 2550)
IF NOT EXISTS;

// INSERT price Спасск -> Артем
INSERT INTO tda_dev.price_ctc (id, cityFrom, cityTo, price)
VALUES (1981004752, 'Спасск', 'Артем', 3580)
IF NOT EXISTS;

// INSERT price Спасск -> Барабаш
INSERT INTO tda_dev.price_ctc (id, cityFrom, cityTo, price)
VALUES (-1244484369, 'Спасск', 'Барабаш', 4100)
IF NOT EXISTS;

// INSERT price Спасск -> Дальнереченск
INSERT INTO tda_dev.price_ctc (id, cityFrom, cityTo, price)
VALUES (812563707, 'Спасск', 'Дальнереченск', 3290)
IF NOT EXISTS;