# TODO: Change file format to .properties
# TODO: Get variables from secrets
# TODO: How to work with secrets in Spring

project:
    version: @projectVersion@

server:
    servlet-path: /mvc

javamelody:
    init-parameters:
        monitoring-path: /service/monitoring
    advisor-auto-proxy-creator-enabled: false

spring:
    jpa:
        hibernate:
            ddl-auto: validate

hibernate:
    search:
        default:
            directory_provider: filesystem
            indexBase: ./application/out/data/index/default
