
server:
    servlet-path: /mvc

---
spring:
    profiles: local

server:
    port: 8087

cassandra:
    host: localhost
    port: 9042
    keyspace: tda

---
spring:
    profiles: dev

---
spring:
    profiles: prod

---