project:
    version: @projectVersion@

server:
    servlet-path: /mvc

javamelody:
    init-parameters:
        monitoring-path: /service/monitoring

spring:
    data:
        cassandra:
            keyspace-name: tda
            contact-points: localhost
            username: cassandra
            password: cassandra

---
spring:
    profiles: local

server:
    port: 8087

---
spring:
    profiles: dev

---
spring:
    profiles: prod

javamelody:
    enabled: false

---