project:
    version: @projectVersion@

server:
    servlet-path: /mvc

javamelody:
    init-parameters:
        monitoring-path: /service/monitoring

---
spring:
    profiles: local
    data:
        cassandra:
            keyspace-name: tda
            contact-points: localhost
            username: cassandra
            password: cassandra

server:
    port: 8087

keycloak:
    auth-server-url: http://sso.vostok.systems/auth
    realm: vostok
    resource: tda-local
    ssl-required: external
    credentials:
        secret: 167210ac-c1dd-49c3-b5c0-c443791a6ef2
    use-resource-role-mappings: true

---
spring:
    profiles: dev

---
spring:
    profiles: prod
    data:
        cassandra:
            keyspace-name: tda
            contact-points: 10.1.55.80
            port: 9042
            username: cassandra
            password: cassandra

javamelody:
    enabled: false

keycloak:
    auth-server-url: http://sso.vostok.systems/auth
    realm: vostok
    resource: tda
    ssl-required: external
    credentials:
        secret: d8595f21-437d-4d06-9aaf-c974795c75af
    use-resource-role-mappings: true
---