project:
    version: @projectVersion@

server:
    servlet-path: /mvc

javamelody:
    init-parameters:
        monitoring-path: /service/monitoring
    advisor-auto-proxy-creator-enabled: false

spring:
    profiles:
        active: local

---
spring:
    profiles: local
    data:
        cassandra:
            keyspace-name: tda
            contact-points: localhost
            username:
            password:
    datasource:
        url: jdbc:postgresql://192.168.99.100:5432/tda
        username: postgres
        password: admin
    jpa:
        hibernate:
            ddl-auto: create-drop

sso.enabled.local: false
sso:
    config: sso/sso-local.json

server:
    port: 8087





---
spring:
    profiles: docker
    data:
        cassandra:
            keyspace-name: tda_prod
            contact-points: 172.18.0.22
            port: 9042
            username:
            password:

server:
    contextPath: /tda

javamelody:
    enabled: true

sso.enabled.prod: true
sso:
    config: /WEB-INF/classes/sso/sso-prod.json

---
spring:
    profiles: integration
    data:
        cassandra:
            keyspace-name: tda
            contact-points: localhost
            port: 9042
            username:
            password:

server:
    contextPath: /tda

javamelody:
    enabled: false

sso.enabled.integration: false
sso:
    config: /WEB-INF/classes/sso/sso-local.json