
server:
    servlet-path: /mvc

javamelody:
    init-parameters:
      monitoring-path: /system/monitoring

---
spring:
    profiles: local

server:
    port: 8087

cassandra:
    host: localhost
    port: 9042
    keyspace: tda

---
spring:
    profiles: dev

---
spring:
    profiles: prod

javamelody:
    enabled: false

---