project:
    version: @projectVersion@

server:
    servlet-path: /mvc

javamelody:
    init-parameters:
        monitoring-path: /service/monitoring
    advisor-auto-proxy-creator-enabled: false

spring:
    jpa:
        hibernate:
            ddl-auto: validate
