project:
    version: @projectVersion@

server:
    servlet-path: /mvc

javamelody:
    init-parameters:
        monitoring-path: /service/monitoring

---
spring:
    profiles: local
    data:
        cassandra:
            keyspace-name: tda
            contact-points: localhost
            username: cassandra
            password: cassandra

sso.enabled.local: true
sso:
    config: sso/sso-local.json

server:
    port: 8087

---
spring:
    profiles: dev

---
spring:
    profiles: prod
    data:
        cassandra:
            keyspace-name: tda
            contact-points: 172.18.0.22
            port: 9042
            username: cassandra
            password: cassandra

server:
    contextPath: /tda

javamelody:
    enabled: false

sso.enabled.prod: true
sso:
    config: /WEB-INF/classes/sso/sso-prod.json

---
spring:
    profiles: integration
    data:
        cassandra:
            keyspace-name: tda
            contact-points: localhost
            port: 9042
            username: cassandra
            password: cassandra

server:
    contextPath: /tda

javamelody:
    enabled: false

sso.enabled.integration: false
sso:
    config: /WEB-INF/classes/sso/sso-local.json